### PR TITLE
SmartLock lock/unlock support changes merged to beta branch

### PR DESCRIPTION
**Pull request by icortes95**
Hope this is what I'm supposed to be doing!

Same as changes in #364.

### CODE REVIEW

**Comment by schliemann** [comment]
Looks good to me.

**Comment by lenoxys** [comment]
I'm good too

**Review by lenoxys — APPROVED** [review]

**Review by schliemann — APPROVED** [review]

**Comment by kunwarsethi** [comment]
I'm getting `[14/03/2022, 09:54:14] TypeError: Cannot read properties of null (reading '0')
    at P2PClientProtocol.incLockSequenceNumber (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/p2p/session.ts:1620:78)
    at Station.lockDevice (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/http/station.ts:3192:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[14/03/2022, 09:54:14] Got SIGTERM, shutting down Homebridge...0`

when trying to unlock the Smart Lock T8520. I've tried uninstalling and reinstalling Beta 33.

**Comment by kunwarsethi** [comment]
Okay so changing switching to an account with Admin privilege's doesn't throw any errors. However, I was only able to get the door to lock once and since then it just hangs. In the debug I can see -

`[3/14/2022, 4:39:11 PM] [EufySecurity-1.1.1-beta.33] DEBUG: Front Door Triggered SET LockTargetState 1
[3/14/2022, 4:39:12 PM] [EufySecurity-1.1.1-beta.33] DEBUG: Setting snapshotPromise to undefined.
[3/14/2022, 4:39:13 PM] [EufySecurity-1.1.1-beta.33] DEBUG: Front Door Property Changes: lockStatus { value: 3, timestamp: '1647290353828' }`

But nothing happens after that. Sample for unlocking: (LockTargetState 0 and lockStatus {value: 4..), nothing happens.

**Pull request merged**
