### PR TITLE
Adding lock/unlock support for T8520 (#354)

### PR DESCRIPTION
**Pull request by icortes95**
Now that the eufy-security-client has been updated, I bumped it to the latest version (1.6.6) and have added support for un/locking the Smart Lock Touch & Wi-Fi (T8520) through HomeKit. Addresses #354.

I have tested that both lock and unlock work. Also, notifications for when the events happen are typically triggered right away now, but I think that's all due to the changes in the eufy-security-client and not anything I did.

This is my first time contributing to an open source project, so please let me know if I'm not going about this the right way. Especially regarding the package-lock.json file. That was just what was generated during my development/testing and I'm not sure if all those changes are supposed to be included.

### CODE REVIEW

**Comment by kunwarsethi** [comment]
Tried adding these changes in "/usr/local/lib/node_modules/homebridge-eufy-security/package-lock.json", "package.json" and  "/usr/local/lib/node_modules/homebridge-eufy-security/dist/accessories/SmartLockAccessory.js" but I get an error when I try to use the lock -

`TypeError: Cannot read properties of null (reading '0')
    at P2PClientProtocol.incLockSequenceNumber (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/p2p/session.ts:1620:78)
    at Station.lockDevice (/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/http/station.ts:3192:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by icortes95** [comment]
@kunwarsethi  I'm not sure you can just replace files like that. I had to pull my fork of homebridge-eufy-security,  make the changes to the package.json and src/accessories/SmarLockAccessory.ts. Then do an `npm install`, `npm run build` to build your version. Finally, run `npm link` in your plugin directory and enable `-D` debug mode in the Homebridge settings so Homebridge can pick up your version,

**Comment by lenoxys** [comment]
hey thanks for your contribution.
Can you sync changes from beta branch and then push only the
[src/accessories/SmartLockAccessory.ts](https://github.com/samemory/homebridge-eufy-security/pull/364#diff-577a0589292ee40ff1d90ed106d78baf69b00a77101ea1f898293e79bdfff168)

thanks!

**Comment by icortes95** [comment]
Hi! I'm a bit confused as to what I have to do. Maybe it stems from the face that I created this PR from master instead of beta to begin with.

Should I update my beta branch and then merge it into my master branch (since that's where this PR is coming from)? Then push those changes which will show up here?

Sorry if these are really noob questions, for some reason we use different version control software at work instead of git, so I'm not very familiar with the standard procedure.

**Comment by lenoxys** [comment]
Hi, no worries. We're working on the beta release ATM. Could you just use the beta branch, push your modifications and then PR from your beta to ours ?

**Comment by lenoxys** [comment]
Thanks closing this one

**Pull request closed without merging**
