### PR TITLE
Adding Face recognition doorbell

### PR DESCRIPTION
**Pull request by Kaspermaat**
Hi There,

I was wondering if it is possible to add Face recognition to the doorbell?
Same like the 2K Camera's.

Thanks.

### CODE REVIEW

**Comment by schliemann** [comment]
@Kaspermaat Not quite sure what you mean?

**Comment by Kaspermaat** [comment]
> @schliemann 
The ‘normal’ cameras have a face option in Homekit for face recognition. 
See underneath print screen:
27B93DA7-6281-4CC5-A104-7F35C613F4DC

**Comment by schliemann** [comment]
What features are you looking to add that is not already in the plugin? You have created a PR to a branch that is not currently particularly active.

**Comment by Kaspermaat** [comment]
Whoops, that’s my fault then for the PR, sorry for that. The face recognition isn’t showing up at the doorbell camera so I guess it isn’t in yet.

**Comment by schliemann** [comment]
Your camera is native in homekit. Homebridge doesn't support this.

https://www.google.dk/amp/s/amp.reddit.com/r/HomeKit/comments/hmpg02/has_anyone_gotten_facial_recognition_for/

**Comment by lenoxys** [comment]
closing this PR. Please use Issue.

**Pull request closed without merging**
