### PR TITLE
Motion Sensor Fix, trigger when motion is detected

### PR DESCRIPTION
**Pull request by lenoxys**

### CODE REVIEW

**Comment by schliemann** [comment]
Awesome work 👍🏻

**Review by lenoxys — COMMENTED** [review]
#94 should be fixed as well

**Comment by schliemann** [comment]
I don't use the schema for anything but removing off mode is probably premature since I'm still communicating with Bropat.

**Comment by lenoxys** [comment]
> I don't use the schema for anything but removing off mode is probably premature since I'm still communicating with Bropat.

Ha sorry do you want me to revert back ? It's just creating issue until we have proper feedback from bropat.

**Comment by schliemann** [comment]
No. Keep it. You are right. It prevents users using config ui or hoobs from reporting a known error.

**Pull request merged**
