### PR TITLE
Fix the motion sensor and Removing test code and tentative to fix bug #44

### PR DESCRIPTION
**Pull request by lenoxys**

### CODE REVIEW

**Review by schliemann — COMMENTED** [review]
The problem is not the use of .value. The problem is that indoor cameras doesn't expose isEnabled. We should add a check if isEnabled is defined here instead https://github.com/samemory/homebridge-eufy-security/blob/108274f5c620c61ad5f865dfc1155c80225119ef/src/securityCameraAccessory.ts#L82

**Comment by lenoxys** [comment]
> The problem is not the use of .value. The problem is that indoor cameras doesn't expose isEnabled. We should add a check if isEnabled is defined here instead
> 
> https://github.com/samemory/homebridge-eufy-security/blob/108274f5c620c61ad5f865dfc1155c80225119ef/src/securityCameraAccessory.ts#L82

can we put that part on the hasbattery condition ?

**Comment by schliemann** [comment]
Yeah. The concept is the same.

**Review by schliemann — COMMENTED** [review]
I think we should check on the method instead of device type. Otherwise we have to maintain what devices support.

**Comment by lenoxys** [comment]
Can we discuss on slack ?
https://join.slack.com/t/homebridgeeuf-lmq5398/shared_invite/zt-rwjys8o6-eOtB6WVAyu_GZkoBEgstew

**Pull request merged**
