### PR TITLE
Possible fix for T8420 camera

### PR DESCRIPTION
**Pull request by fullphat**
Specifically, the HomeKit Alarm System created for the camera not responding to changes in the Eufy app

### CODE REVIEW

**Comment by lenoxys** [comment]
Does floodlight provide Alarm on EufyApp ?

**Comment by schliemann** [comment]
I need some time to verify the change.

**Comment by fullphat** [comment]
> I need some time to verify the change.

That's fine!  This is my first foray into git PRs and branches, and my first foray into Javascript, node and HomeBridge plugin development so I may well have got many things wrong! 😊  Just let me know if you have any queries. 👍🏼

**Comment by fullphat** [comment]
For info, the T8420 does support the ability to arm, disarm, schedule and geo-fence and you can enable any of motion detection, push notifications and siren for the home or away modes:

5FD9852F-AA20-4AB6-A2F6-01D78D7935DF

So having it as an Alarm System is HomeKit is really helpful.  One thing I have spotted as well is that when the plugin starts, there is a log message along the lines of "Device is station but type is 3 might imply errors".

**Comment by lenoxys** [comment]
> For info, the T8420 does support the ability to arm, disarm, schedule and geo-fence and you can enable any of motion detection, push notifications and siren for the home or away modes:
> 
> 
> 
> 5FD9852F-AA20-4AB6-A2F6-01D78D7935DF
> 
> 
> 
> So having it as an Alarm System is HomeKit is really helpful.  One thing I have spotted as well is that when the plugin starts, there is a log message along the lines of "Device is station but type is 3 might imply errors".
> 
> 
> 
> 
> 
> 

Did you have a look on my comment on your PR ?

This is normal behavior to have this log message. Camera act as a station but doesn't have all station capabilities. That's why you get the warning message.

**Comment by fullphat** [comment]
> > So having it as an Alarm System is HomeKit is really helpful.  One thing I have spotted as well is that when the plugin starts, there is a log message along the lines of "Device is station but type is 3 might imply errors".
> 
> This is normal behavior to have this log message. Camera act as a station but doesn't have all station capabilities. That's why you get the warning message.
> 

That's fine.


> Btw, did you have a look on my comment on your PR ?
> 
> [#326 (review)](https://github.com/samemory/homebridge-eufy-security/pull/326#pullrequestreview-849121206)

Apologies - I can't find it?

**Comment by schliemann** [comment]
@fullphat I'll take a look at this PR when I have pushed the changes to snapshot to the beta.

**Comment by lenoxys** [comment]
- Could you not point to a specific model while naming this function?
    - It would rather inverse have isAlarmStation than isFloodlight and avoid creating the object
    - Escape it like this
`if (!isAlarmStation()){
this.log.debug('does not provide alarm capabilities')
return;
}`

**Comment by fullphat** [comment]
> * isAlarmStation



> Could you not point to a specific model while naming this function?
> * It would rather inverse have isAlarmStation than isFloodlight and avoid creating the object
> * Escape it like this
>   `if (!isAlarmStation()){ this.log.debug('does not provide alarm capabilities') return; }`

Yes, I can do - is `isAlarmStation()` already defined somewhere?  If not, how do I test if something is an alarm station?

Don't forget that the floodlight camera does provide an alarm function; it's more that it's its own station.

**Comment by fullphat** [comment]
> * isAlarmStation



> Could you not point to a specific model while naming this function?
> * It would rather inverse have isAlarmStation than isFloodlight and avoid creating the object
> * Escape it like this
>   `if (!isAlarmStation()){ this.log.debug('does not provide alarm capabilities') return; }`

Yes, I can do - is `isAlarmStation()` already defined somewhere?  If not, how do I test if something is an alarm station?

Don't forget that the floodlight camera does provide an alarm function; it's more that it's its own station.

**Comment by schliemann** [comment]
@fullphat Has this been fixed by some of @kare sake fixes?

**Comment by fullphat** [comment]
> @fullphat Has this been fixed by some of @karesake fixes?

I think it might have been but I haven't been able to check it properly yet.  Give me a couple of days to confirm?

**Pull request closed without merging**
